//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public int Ma { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<int> MaHopDong { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
