//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuaChua
    {
        public int MaSuaChua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<double> ChiPhi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaXe { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
